### ISSUE TITLE
Apple Music crashes when skipping multiple songs at once.

### ISSUE THREAD

**Issue by dsyomichev** [bermudalocket/MeltedCrayons#31] opened 2020-03-15 03:29 UTC
**Describe the bug:** Apple music randomly crashes when quickly skipping multiple songs, regardless of whether it is skipping forward or back.

**To Reproduce Steps to reproduce the behavior:** 

1. Go to Apple Music.
2. Play a playlist.
3. Quickly press skip button several times.
4. Apple music crashes.

**Expected behavior:** Skip multiple songs repeatedly without crashing.

**Smartphone:**

Device: iPhone 8
OS: IOS 13.3

**Additional Context:** 

- Doesn't occur when MeltedCrayons.dylib is disabled using iCleaner Pro
- The amount of skips before a crash seems to be random.
- Apple music diagnostic log. (Compressed)
[Music-2020-03-12-192855.ips.zip](https://github.com/bermudalocket/MeltedCrayons/files/4333742/Music-2020-03-12-192855.ips.zip)

**Comment by bermudalocket** [comment] 2020-03-15 20:08
Should be fixed in 1.0.2b71. Thanks for the thread dump.

**Comment by El-MokoMoko** [comment] 2020-03-15 22:24
Not fixed for me in 1.0.2b71
iPhone X 13.3.1 Checkra1n

**Comment by bermudalocket** [comment] 2020-03-15 22:48
@El-MokoMoko Damn. I can't reproduce that and I'm on the same device and version. I tried with a downloaded playlist, an Apple Music playlist, and the radio. Can you give me a little more info?

**Comment by tychoregter** [comment] 2020-03-15 23:32
> @El-MokoMoko Damn. I can't reproduce that and I'm on the same device and version. I tried with a downloaded playlist, an Apple Music playlist, and the radio. Can you give me a little more info?

I have the same issue, it randomly happens once in a while. I honestly don’t really have any extra steps to take to make it crash besides quickly skipping songs in both downloaded and non-downloaded playlists. I use an iPhone X on 13.3.1.

**Comment by El-MokoMoko** [comment] 2020-03-16 01:23
First it’s not a conflict with another tweak i tried with all my tweak disabled in iCleaner and i can’t share you a crashlog Cr4shed doesn’t give me one :/

**Comment by El-MokoMoko** [comment] 2020-03-16 01:29
Oh sorry i had my reportercrash deamon disabled :/ here a crashlog : https://pastebin.com/GvjFeCyz
Good luck ;)

**Comment by El-MokoMoko** [comment] 2020-03-17 18:28
Still crashing in b82-2

**Comment by bermudalocket** [comment] 2020-03-17 18:54
@El-MokoMoko Can you provide an updated crash log? This is driving me crazy...

**Comment by El-MokoMoko** [comment] 2020-03-17 19:37
I would like to send you one but now the app crash without crashlog i don’t know why :/

**Comment by El-MokoMoko** [comment] 2020-03-17 19:41
Sorry my cr4shed tweak was broken 
Here a new crashlog : https://pastebin.com/5JZxKEzF

**Comment by bermudalocket** [comment] 2020-03-17 21:43
Thanks, @El-MokoMoko. I've pushed build 87 to Twickd and I'm keeping my fingers crossed. I might have to do some rethinking if this doesn't fix it.

**Comment by El-MokoMoko** [comment] 2020-03-17 22:06
Okay so it crash less quickly but still 
Here my crashlog : https://pastebin.com/8ftvVv0q

**Comment by El-MokoMoko** [comment] 2020-03-18 13:31
Hey good news ! I skipped songs for 10 minutes and no crash it seems to be fixed 
Good job and thanks ;)

**Comment by dsyomichev** [comment] 2020-03-18 15:56
Same here, doesn't seem to crash anymore with the newest update.

**Comment by bermudalocket** [comment] 2020-03-18 17:22
Awesome!!! Thanks for sticking with me.

**Closed as completed by bermudalocket** 2020-03-18 17:22 UTC
